# Chap2 Variables, Types and Operations

用户可以明确传递给一个函数的变量类型——可以提升运行速度。因此深入理解Julia的变量规则是十分有必要的。

这一章中将包含以下内容：
* 变量、命名规则，注释
* 变量类型
* 整型变量
* 浮点型变量
* 基本的数学函数以及运算符
* 分数以及复数
* 字符
* 字符串
* 通常的表达式（Regular expressions）
* 范围以及arrays
* 日期与时间
* 作用域和常数

# 变量、命名规则，注释

In [4]:
#Julia和其他语言不同，Julia明确区分character和string
#双引号只能用于string，单引号只能用于character
char1 = 'a'
println(char1)
str1 = "let me see"
println(str1)

a
let me see


In [6]:
char2 = 'aw'

LoadError: syntax: character literal contains multiple characters

In [7]:
str2 = "a"#由于字符串是可以包含任意数量的字符的，因此这也是合法的。

"a"

In [8]:
x = 42
typeof(x)

Int64

In [9]:
x = "I am Julia"
typeof(x)

String

### 在Julia中我们并不需要事先声明一个变量的类型，但是我们一定要首先定义一个量——和Python一样。在Julia中任何一个语句都是一个expression，这和其他语言很不一样，因此在REPL中运行是非常棒的——我们每一步都能看到具体的expression的值。

In [10]:
"""
Julia 是一个强类型语言！字符串就不能和数相加
"""
x = "I am Julia"
y = 42
x + y

LoadError: MethodError: no method matching +(::String, ::Int64)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::Complex{Bool}, ::Real) at complex.jl:301
  +(!Matched::Missing, ::Number) at missing.jl:115
  ...

In [11]:
x = 3.5
y = 42
x + y

45.5

In [12]:
#这里的；就和C++一样了，作为分隔符号，代表第一个语句的结束并且不让分号前的语句的结果输出
x = 2; y = 3; x+y

5

In [13]:
"""
Julia的变量命名是我见过的除了Mathematica之外最强大的语言了，你啥都能打出来
"""
ω1 = 2
δ2 = 3
α_ = 4

4

In [14]:
# Calculate the gravitational acceleration grav_acc:
gc = 6.67e-11 # gravitational constant in m3/kg s2
mass_earth = 5.98e24 # in kg
radius_earth = 6378100 # in m
grav_acc = gc * mass_earth / radius_earth^2 # 9.8049 m/s2

9.804927114935674

In [21]:
printstyled("I love Julia!", color=:red)

I love Julia!

In [36]:
#print() display() show()
x = "I love Julia!";
println(x)
println(x)
show(x)
display(x)#它总是第一个显示出来

"I love Julia!"

I love Julia!
I love Julia!
"I love Julia!"

In [38]:
x :: String
x = 1

LoadError: TypeError: in typeassert, expected String, got a value of type Int64

In [39]:
x = "Have a try"

"Have a try"

In [40]:
#这里有很有趣的一点是我们要注意，给定类型的语句是在变量后面的，这和C++就不一样。在C++中我们是用int a = 1来定义变量的。
(2+3) :: String# (expr) :: TypeName 用来判断expr是否是TypeName类型的变量

LoadError: TypeError: in typeassert, expected String, got a value of type Int64

我们最好去写type-stable的代码，所谓type-stable的含义指的是整个代码中一个变量的类型是绝对不变的，这对代码的performance有很大的帮助。

In [47]:
#=A very good Example=#
function sumofsins1(n::Integer)
    r = 0#Integer64
    for i in 1:n
        r += sin(3.4)#Int→FLoat
    end
    return r
end

function sumofsins2(n::Integer)
    r = 0.0#Float64
    for i in 1:n
        r += sin(3.4)#Float→Floar(Actcually doesn't vary)
    end
    return r
end

sumofsins2 (generic function with 1 method)

In [49]:
sumofsins1(100_000)
sumofsins2(100_000)

-25554.110202663698

In [55]:
100_100 == 100100

true

In [66]:
#很奇怪。。。在我的电脑上这俩基本没啥区别
@time [sumofsins1(100_000) for i in 1:100];
@time [sumofsins2(100_000) for i in 1:100];

  0.136297 seconds (112.08 k allocations: 6.181 MiB)
  0.062957 seconds (107.16 k allocations: 5.963 MiB)


In [67]:
code_llvm(sumofsins1, (Int, ))  


;  @ In[63]:1 within `sumofsins1'
define { %jl_value_t*, i8 } @julia_sumofsins1_1684([8 x i8]* noalias nocapture align 8 dereferenceable(8), i64) {
top:
;  @ In[63]:3 within `sumofsins1'
; ┌ @ range.jl:5 within `Colon'
; │┌ @ range.jl:280 within `UnitRange'
; ││┌ @ range.jl:285 within `unitrange_last'
; │││┌ @ operators.jl:350 within `>='
; ││││┌ @ int.jl:441 within `<='
       %2 = icmp sgt i64 %1, 0
; │││└└
     %3 = select i1 %2, i64 %1, i64 0
; └└└
  br i1 %2, label %L11, label %union_move8

L11:                                              ; preds = %L49, %top
; ┌ @ range.jl:620 within `iterate'
   %4 = phi double [ %value_phi3, %L49 ], [ 0.000000e+00, %top ]
   %.sroa.014.0 = phi i64 [ %8, %L49 ], [ 0, %top ]
   %tindex_phi = phi i8 [ 1, %L49 ], [ 2, %top ]
   %value_phi2 = phi i64 [ %7, %L49 ], [ 1, %top ]
; └
;  @ In[63]:4 within `sumofsins1'
  switch i8 %tindex_phi, label %L37 [
    i8 1, label %L39
    i8 2, label %L33
  ]

L33:                                              ;

In [68]:
 code_llvm(sumofsins2, (Int, ))  


;  @ In[63]:9 within `sumofsins2'
define double @julia_sumofsins2_1685(i64) {
top:
;  @ In[63]:11 within `sumofsins2'
; ┌ @ range.jl:5 within `Colon'
; │┌ @ range.jl:280 within `UnitRange'
; ││┌ @ range.jl:285 within `unitrange_last'
; │││┌ @ operators.jl:350 within `>='
; ││││┌ @ int.jl:441 within `<='
       %1 = icmp sgt i64 %0, 0
; │││└└
     %2 = select i1 %1, i64 %0, i64 0
; └└└
  br i1 %1, label %L11, label %L37

L11:                                              ; preds = %L11, %top
  %value_phi2 = phi double [ %3, %L11 ], [ 0.000000e+00, %top ]
  %value_phi3 = phi i64 [ %5, %L11 ], [ 1, %top ]
;  @ In[63]:12 within `sumofsins2'
; ┌ @ float.jl:401 within `+'
   %3 = fadd double %value_phi2, 0xBFD05AC910FF4C6C
; └
; ┌ @ range.jl:624 within `iterate'
; │┌ @ promotion.jl:398 within `=='
    %4 = icmp eq i64 %value_phi3, %2
; │└
   %5 = add nuw i64 %value_phi3, 1
; └
  br i1 %4, label %L37, label %L11

L37:                                              ; preds = %L11, %top
  %value_

In [77]:
x=1
println(isa(x, Float64))
println(isa(x, Integer))
println(isa(x, Any))
println(isa(x, Nothing))

false
true
true
false


In [85]:
"""
Everything in Julia has a type, including types themselves, which are of type `DataType`
"""
typeof(Int64)

Core.typeof

In [86]:
typeof(Int)

DataType

In [87]:
typeof(Float64)

DataType

In [97]:
Int64("hello")

LoadError: MethodError: no method matching Int64(::String)
Closest candidates are:
  Int64(!Matched::Union{Bool, Int32, Int64, UInt32, UInt64, UInt8, Int128, Int16, Int8, UInt128, UInt16}) at boot.jl:708
  Int64(!Matched::Ptr) at boot.jl:718
  Int64(!Matched::Float32) at float.jl:706
  ...

In [105]:
Float64(10)

10.0

In [108]:
Int(2.5::Float64)

LoadError: InexactError: Int64(2.5)

In [110]:
?InexactError:Int64(2.5)

InexactError: InexactError: Int64(2.5)

In [111]:
typemax(Int16)

32767

In [112]:
typemax(Int32)

2147483647

In [113]:
typemax(Int64)

9223372036854775807

In [114]:
typemax(Int)

9223372036854775807

In [115]:
ans+1

-9223372036854775808

In [116]:
BigInt(9223372036854775808)

9223372036854775808

In [117]:
big(9223372036854775809)

9223372036854775809

In [125]:
!true

false

In [126]:
0<x<3

true

In [128]:
#comparisons can be chained after one another
x = 5
3<x>8

false

In [129]:
typeof(3.14)

Float64

In [130]:
typeof(π)

Irrational{:π}

In [131]:
π

π = 3.1415926535897...

In [132]:
typeof(4e-14)

Float64

In [134]:
typeof(3.14f0)#这是单精度形变量的定义，注意必须这么写 e⟹f

Float32

In [137]:
println(typeof(2.5f2))
println(typeof(2.5*10^2))

Float32
Float64


In [143]:
Inf

Inf

In [144]:
0.1+0.2

0.30000000000000004

In [145]:
#不要用==去比较浮点数
0.1 + 0.2 == 0.3

false

In [146]:
0.1 + 0.2 >= 0.3

true

In [147]:
bitstring(3)#二进制的表示

"0000000000000000000000000000000000000000000000000000000000000011"

In [148]:
bitstring(3.3)

"0100000000001010011001100110011001100110011001100110011001100110"

In [149]:
round(3.3)#取整数部分

3.0

In [150]:
round(-2.3)#取整数部分

-2.0

In [151]:
rand(5)

5-element Array{Float64,1}:
 0.568830463666814
 0.32196745356183243
 0.7826240316449131
 0.6038807876050349
 0.3608198524433819

In [152]:
a = b = c = d = e = 1 

1

In [153]:
b = 2
a

1

In [154]:
a = 1 ; b = 2; c = 3; d = 4
a, b = c, d

(3, 4)

In [155]:
a, b

(3, 4)

In [156]:
a, b = b, a

(4, 3)

In [157]:
a, b

(4, 3)

In [158]:
3.2 + 7.1im

3.2 + 7.1im

In [159]:
typeof(1+1im)

Complex{Int64}

In [160]:
(3.2 + 7.1im)*(1+1im)

-3.8999999999999995 + 10.3im

In [161]:
exp(1+1im)

1.4686939399158851 + 2.2873552871788423im

In [165]:
abs(1+1im)

1.4142135623730951

In [163]:
√2

1.4142135623730951

In [167]:
complex(3,4)

3 + 4im

In [168]:
3//4 #有理数

3//4

In [171]:
typeof('A')

Char

In [172]:
typeof("A")

String

In [173]:
typemax(Char)

'\xff\xff\xff\xff': Malformed UTF-8 (category Ma: Malformed, bad data)

In [174]:
typemin(Char)

'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

In [175]:
Char(65)

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [176]:
Char(97)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [177]:
s = "Hello, Julia"
s[2]

'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [179]:
s[2] = 'z'

LoadError: MethodError: no method matching setindex!(::String, ::Char, ::Int64)

In [180]:
s[end]

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [181]:
s[begin]

'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)

In [182]:
s[1]

'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)

In [184]:
length(s)

12

In [188]:
str2 = "I am the α: the beginning"

"I am the α: the beginning"

In [189]:
str2[10]#事实上一个α占两个位置，所以取[11]会报错

'α': Unicode U+03B1 (category Ll: Letter, lowercase)

In [190]:
str2[11]

LoadError: StringIndexError("I am the α: the beginning", 11)

In [191]:
str2[12]

':': ASCII/Unicode U+003A (category Po: Punctuation, other)

In [192]:
length(str2)

25

In [193]:
lastindex(str2)

26

In [194]:
str2[26]

'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)

In [195]:
for char in str2
    print(char)
end

I am the α: the beginning

In [200]:
s[3:5]

"llo"

In [201]:
s[3:end]

"llo, Julia"

In [202]:
'A' == "A"

false

In [207]:
a = 5
println("a = $a")

a = 5


In [208]:
a = 2; b = 3;
println("a*b = $(a*b)")

a*b = 6


In [209]:
println("I want to print \$ symbol")

I want to print $ symbol


In [210]:
"ABC" * "DEF"

"ABCDEF"

In [211]:
string("abc", "def", "ghi")

"abcdefghi"

In [212]:
:green

:green

In [213]:
methodswith(String)

[1] uuid5(ns::Base.UUID, name::String) in UUIDs at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/UUIDs/src/UUIDs.jl:117
[2] crc32c(s::String, crc::UInt32) in CRC32c at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/CRC32c/src/CRC32c.jl:39
[3] crc32c(s::String) in CRC32c at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/CRC32c/src/CRC32c.jl:39
[4] subscribe(socket::ZMQ.Socket, filter::Union{Array{UInt8,1}, String}) in ZMQ at /Users/zhonghaowen/.julia/packages/ZMQ/R3wSD/src/sockopts.jl:75
[5] unsubscribe(socket::ZMQ.Socket, filter::Union{Array{UInt8,1}, String}) in ZMQ at /Users/zhonghaowen/.julia/packages/ZMQ/R3wSD/src/sockopts.jl:75
[6] @pkg_str(__source__::LineNumberNode, __module__::Module, str::String) in Pkg.REPLMode at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:460
[7] hmac_sha1(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[8] hmac_sha224(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[9] hmac_sha256(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[10] hmac_sha2_224(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[11] hmac_sha2_256(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[12] hmac_sha2_384(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[13] hmac_sha2_512(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[14] hmac_sha384(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[15] hmac_sha3_224(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[16] hmac_sha3_256(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[17] hmac_sha3_384(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[18] hmac_sha3_512(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[19] hmac_sha512(key::Array{UInt8,1}, str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:63
[20] sha1(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:61
[21] sha224(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:61
[22] sha256(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:61
[23] sha2_224(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:61
[24] sha2_256(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:61
[25] sha2_384(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:61
[26] sha2_512(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/SHA/src/SHA.jl:61
[27] sha384(str::String) in SHA at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.

In [216]:
replace("I luve Julia","u"=>"o")

"I love Jolia"

In [217]:
replace("I love her","er"=>"im")

"I love him"

In [219]:
split("34,WTF,??",",")

3-element Array{SubString{String},1}:
 "34"
 "WTF"
 "??"

In [220]:
split("34,WTF,??","a")#如果没有那就不分割

1-element Array{SubString{String},1}:
 "34,WTF,??"

In [222]:
split("34  WTF  ??")#如果不指定就是按空格

3-element Array{SubString{String},1}:
 "34"
 "WTF"
 "??"

In [224]:
name = "Pascal"
using Printf
@printf("Hello, %s \n", name)#returns Hello, Pascal

Hello, Pascal 


In [225]:
using Printf
# d for integers:
@printf("%d\n", 1e5)

100000


In [226]:
x = 7.35679
@printf("X = %0.3f\n", x)

X = 7.357


In [227]:
aa = 1.52323213213123
bb = 2.4353453234646457
@printf("%.2f %.2f\n", aa, bb)

1.52 2.44


In [233]:
str = @sprintf("%0.3f", x)
show(str)
println()
println(str)

"7.357"
7.357


In [236]:
print(VersionNumber)

VersionNumber

In [237]:
typeof(VersionNumber)

DataType

In [1]:
"""
正则表达式我个人感觉可能在科学计算中不会起到太大作用，一
般在一些软件的项目中可能会用到，作为🔑学习，而不苛求细节。
"""
#Regular expression 正则表达式
#+用来连接任何非空的字符串
email_pattern = r".+@.+"
input = "john.doe@mit.edu"
println(occursin(email_pattern, input)) #>true

true


In [3]:
visa = r"^(?:4[0-9]{12}(?:[0-9]{3})?)$"
input = "4457418557635128"
occursin(visa, input)
if occursin(visa, input)
    println("credit card found")
    m = match(visa, input)
    println(m.match)
    println(m.offset)#at what position the matching begins. Here, it is 1.
    println(m.offsets)
end

credit card found
4457418557635128
1
Int64[]


In [4]:
email_pattern = r"(.+)@(.+)"
input = "john.doe@mit.edu"
m = match(email_pattern, input)
println(m.captures)#> Union{Noting,SubString{String}}["John,doe","mit.edu"]

Union{Nothing, SubString{String}}["john.doe", "mit.edu"]


In [6]:
m = match(r"(ju|l)(i)?(a)","Julia")
println(m.match)
println(m.captures)
println(m.offset)
println(m.offsets)

lia
Union{Nothing, SubString{String}}["l", "i", "a"]
3
[3, 4, 5]


In [16]:
"""
Ranges and Arrays
"""

println(typeof(1:1000))

#默认的step=1
for i in 1:9
    println(i)
end

for i in 1:0.5:9
    println(i)
end

UnitRange{Int64}
1
2
3
4
5
6
7
8
9
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5
5.0
5.5
6.0
6.5
7.0
7.5
8.0
8.5
9.0


In [21]:
a = split("A, B, C, D",",")
println(typeof(a))#> Array{SubString{String},1}  1 = dimension
println(show(a))

Array{SubString{String},1}
SubString{String}["A", " B", " C", " D"]nothing


In [22]:
# All the elements gotta be of the same type.

arr = [100, 25, 37]
arra = Any[100, 25, "ABC"]

3-element Array{Any,1}:
 100
  25
    "ABC"

In [23]:
arr2 = [100, 25, "ABC"]
println(arr2)

Any[100, 25, "ABC"]


In [24]:
arr2[1]

100

In [25]:
#Arrays can also be consructed by passing a type of parameter and a number of elements
arr2 = Array{Int64}(undef, 5)# is a 5-element Array{Int64, 1}
show(arr2)

[0, 0, 0, 0, 0]

In [26]:
arr3 = Float64[]
show(arr3)

Float64[]

In [27]:
push!(arr3,1.0)

1-element Array{Float64,1}:
 1.0

In [28]:
pop!(arr3)

1.0

In [29]:
arr3

Float64[]

In [35]:
push!(arr3,1.0,2.0,5.0)
pop!(arr3)
arr3

12-element Array{Float64,1}:
 1.0
 2.0
 1.0
 2.0
 5.0
 1.0
 2.0
 5.0
 1.0
 2.0
 1.0
 2.0

In [36]:
arr4 = collect(1:7)
show(arr4)

[1, 2, 3, 4, 5, 6, 7]

In [37]:
sizehint!(arr2, 10^5)

5-element Array{Int64,1}:
 0
 0
 0
 0
 0

In [38]:
arr = [100, 25, 37]

3-element Array{Int64,1}:
 100
  25
  37

In [39]:
arr[2] = 2
arr

3-element Array{Int64,1}:
 100
   2
  37

In [40]:
eltype(arr)

Int64

In [41]:
length(arr)

3

In [42]:
ndims(arr)

1

In [45]:
size(arr,1)

3

In [46]:
# A for ... in loop over an array is read-only!!!!!

da = collect(1:5)
for n in da
    n *= 2
end
da

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [48]:
# Instead, use an index i, like this
#这个例子告诉我们要用合适的方式去修改array中的值
for i in 1:length(da)
    da[i] *= 2
end
da

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [49]:
zeros(10)#> 10-element Array{Float64,1}: 注意这里是Float64而不是Int64

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [50]:
ones(10)

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [51]:
eqa = range(0, step=10, length = 5)#> 0:10:40
show(eqa)

0:10:40

In [52]:
println(Array{Any}(undef, 4))

Any[#undef, #undef, #undef, #undef]


In [54]:
arr = Array{Any}(undef, 4)
fill!(arr,42)

4-element Array{Any,1}:
 42
 42
 42
 42

In [56]:
v1 = rand(Int32, 5)

5-element Array{Int32,1}:
 -1121381534
  -964389002
 -1168263158
   289420344
  1485447358

In [64]:
"""
Some Common functions for Arrays
A function whose name ends in a ! changes its first argument
"""


b = [12,3]
c = [100,200,300]
show(b)
show(c)
append!(b, c)
show(b)

[12, 3][100, 200, 300][12, 3, 100, 200, 300]

In [65]:
pop!(b)

300

In [66]:
show(b)

[12, 3, 100, 200]

In [67]:
push!(b,42)

5-element Array{Int64,1}:
  12
   3
 100
 200
  42

In [68]:
show(b)

[12, 3, 100, 200, 42]

In [69]:
popfirst!(b)
show(b)

[3, 100, 200, 42]

In [70]:
pushfirst!(b,34)
show(b)

[34, 3, 100, 200, 42]

In [71]:
splice!(b,2)#To remove the second element of the array b
show(b)

[34, 100, 200, 42]

In [72]:
#To testify if the element in b or not?
println(in(42,b))
println(in(43,b))

true
false


In [73]:
sort(b)#sort function won't change the initial array at all

4-element Array{Int64,1}:
  34
  42
 100
 200

In [74]:
println(b)

[34, 100, 200, 42]


In [75]:
sort!(b)#sort! will change it actually!
println(b)

[34, 42, 100, 200]


In [76]:
arr = [1, 8 ,52, 34, 30]
for e in arr
    print("$e ")
end

1 8 52 34 30 

In [77]:
arr = [1, 2, 3]
arr .+ 2

3-element Array{Int64,1}:
 3
 4
 5

In [78]:
arr .*2 

3-element Array{Int64,1}:
 2
 4
 6

In [79]:
arr * 2

3-element Array{Int64,1}:
 2
 4
 6

In [80]:
#To multiple the corresponding element of each array .i.e [a1[1]*a2[1], a1[2]*a2[2], a1[3]*a2[3]]
a1 = [1, 2, 3]
a2 = [4 ,5, 6]
a1 .* a2

3-element Array{Int64,1}:
  4
 10
 18

In [83]:
using LinearAlgebra
@time println(LinearAlgebra.dot(a1,a2))#> 32
@time println(sum(a1 .* a2))

32
  0.000131 seconds (33 allocations: 752 bytes)
32
  0.000121 seconds (36 allocations: 1024 bytes)


In [88]:
repeat([1,2,3],inner=[3])

9-element Array{Int64,1}:
 1
 1
 1
 2
 2
 2
 3
 3
 3

In [89]:
"""
When you assign an array to another array, and then change the first array, both the arrays change!
Because they point to the same object in memory!
"""

a = [1, 2, 4, 6]
a1 = a
show(a1)

[1, 2, 4, 6]

In [91]:
a[4] = 0 
show(a)
show(a1)

[1, 2, 4, 0][1, 2, 4, 0]

In [94]:
"""
Actually, We have some method to avoid it.
"""
a = [1,2,3,4]
b = copy(a)
a[1] = 0
println("a=",a)
println("b=",b)

a=[0, 2, 3, 4]
b=[1, 2, 3, 4]


In [95]:
a = [1,2,3,4]
b = deepcopy(a)
a[1] = 0
println("a=",a)
println("b=",b)

a=[0, 2, 3, 4]
b=[1, 2, 3, 4]


In [97]:
a = [1,[23,3],4,5]
b = copy(a)
a[2] = 0
println("a=",a)
println("b=",b)

a=Any[1, 0, 4, 5]
b=Any[1, [23, 3], 4, 5]


In [98]:
a = [1,[23,3],4,5]
b = deepcopy(a)
a[2] = 0
println("a=",a)
println("b=",b)

a=Any[1, 0, 4, 5]
b=Any[1, [23, 3], 4, 5]


In [99]:
a = "WTF"
a[2]

'T': ASCII/Unicode U+0054 (category Lu: Letter, uppercase)

In [102]:
a[2] = 'F'
show(a)

LoadError: MethodError: no method matching setindex!(::String, ::Char, ::Int64)

In [103]:
"""
Arrays are mutable, and as arugments to a function, they are PASSED BY REFERENCE⟹the function CAN CHANGE them!
"""

a = [1, 2, 3]

function change_array(arr)
    arr[2] = 25
end

change_array(a)
println(a)

[1, 25, 3]


In [105]:
#At here, we did not change the String, actually we change the second element of arr.
arr = ['a', "b", 'c']
arr[2] = 'a'
arr

3-element Array{Any,1}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

In [106]:
arr = ['a', 'b', 'c']
join(arr)

"abc"

In [109]:
println(string(arr))
println(string(arr...)) # ...、⇔ splice

['a', 'b', 'c']
abc


# Dates and Times

In [110]:
time()

1.614008725008341e9

In [111]:
start_time = time()
#long computation
time_elapsed = time() - start_time
println("TIme elapsed: $time_elapsed")

TIme elapsed: 0.0015981197357177734


In [114]:
using Dates
d = Date(2021, 2, 22)

2021-02-22

In [115]:
dt = DateTime(2014, 9, 1, 12 ,30 ,59, 1)

2014-09-01T12:30:59.001

In [116]:
isleapyear(2021)

false

In [120]:
?dayname

search: dayname daysinyear



```
dayname(dt::TimeType; locale="english") -> String
dayname(day::Integer; locale="english") -> String
```

Return the full day name corresponding to the day of the week of the `Date` or `DateTime` in the given `locale`. Also accepts `Integer`.

# Examples

```jldoctest
julia> Dates.dayname(Date("2000-01-01"))
"Saturday"

julia> Dates.dayname(4)
"Thursday"
```


# Scope and constants

* Using global scope variables is not advisable for several reasons, notably the PERFORMANCE!

In [121]:
x = 1.0
x = 1
y ::Float64 = 1.0

LoadError: syntax: type declarations on global variables are not yet supported

In [122]:
function scopetest()
    println(x)
    y :: Float64 = 1.0
end

scopetest (generic function with 1 method)

In [123]:
scopetest()

1


1.0

In [124]:
println(y)

LoadError: UndefVarError: y not defined

## Type annotations can only be used in local scope

### Some code constructs introduce scope blocks. They support local variables.!

* for
* while
* try
* let
* type

In [125]:
"""
Compound expression
"""
x = begin
    a = 5
    2 * a
end
println(x)
println(a)

10
5


In [128]:
x = (a=5;2*a)

10

Variables introduced in it are still known after the expression ends.

In [129]:
const GC = 6.67e-11

6.67e-11

In [130]:
VERSION

v"1.5.3"

In [131]:
ARGS

1-element Array{String,1}:
 "/Users/zhonghaowen/Library/Jupyter/runtime/kernel-546cd0c4-bf26-41f1-a304-a5931b7d4952.json"

In [136]:
pi

π = 3.1415926535897...

In [139]:
GC = 3.14

3.14

In [140]:
GC = 10

LoadError: invalid redefinition of constant GC

In [142]:
GC = 2.3

2.3

In [143]:
GC

2.3

# Julia gets its speed from knowing the correct types

In [144]:
const ARR = [4,7,1]
ARR[1] = 0
show(ARR)

[0, 7, 1]

In [145]:
ARR = [1,2,3]
show(ARR)

[1, 2, 3]

In [146]:
using Statistics
str = "The Gold and Blue Losed a Bit of Its Luster"
println(str)
nchars = length(str)
println("The headline counts $nchars characters")
str2 = replace(str, "Blue" => "Red")

println(str)
println(str2)
println("Here are the characters at position 25 to 30:")
subs = str[25:30]
print("-$(lowercase(subs))-")
println("Here are all the characters:")
for c in str
    println(c)
end

arr = split(str, ' ')
show(arr)

nwords = length(arr)
println("The headline counts $nwords words")
println("Here are all the words")
for word in arr
    println(word)
end

arr[4] = "Red"
show(arr)
println("Convert back to a sentence:")
nstr = join(arr, ' ')
println(nstr)

println("Arrays: caculate sum, mean and standard deviation ")
arr = collect(1:100)
typeof(arr)
println(sum(arr))
println(mean(arr))

The Gold and Blue Losed a Bit of Its Luster
The headline counts 43 characters
The Gold and Blue Losed a Bit of Its Luster
The Gold and Red Losed a Bit of Its Luster
Here are the characters at position 25 to 30:
-a bit -Here are all the characters:
T
h
e
 
G
o
l
d
 
a
n
d
 
B
l
u
e
 
L
o
s
e
d
 
a
 
B
i
t
 
o
f
 
I
t
s
 
L
u
s
t
e
r
SubString{String}["The", "Gold", "and", "Blue", "Losed", "a", "Bit", "of", "Its", "Luster"]The headline counts 10 words
Here are all the words
The
Gold
and
Blue
Losed
a
Bit
of
Its
Luster
SubString{String}["The", "Gold", "and", "Red", "Losed", "a", "Bit", "of", "Its", "Luster"]Convert back to a sentence:
The Gold and Red Losed a Bit of Its Luster
Arrays: caculate sum, mean and standard deviation 
5050
50.5
