# Chap3 Functions

In [1]:
function mult(x,y)#lower-case⟹Convention
    x*y#这么写是被允许的，但是最好不要这样，我们还是用一个retrun语句比较好。
end
mult(3,4)

12

In [2]:
function mult(x,y)
    println("x is $x and y is $y")
    if x == 1
        return y
    end
    x * y
end

mult (generic function with 1 method)

In [3]:
mult(1,4)

x is 1 and y is 4


4

In [5]:
mult(2,4)

x is 2 and y is 4


8

In [7]:
"""
Julia可以直接返回多个值，这个太牛逼了
"""
function multi(n, m)
    n*m, div(n,m), n%m
end

multi (generic function with 1 method)

In [8]:
multi(8,2)

(16, 4, 0)

In [9]:
x, y, z = multi(8,2)

(16, 4, 0)

In [12]:
function varargs(n, m, args...)
    println("arguments : $n $m $args")
end

varargs (generic function with 1 method)

In [15]:
#The args..... argument takes in all the remaining parameters in a tuple
varargs(1,2,[3,4,5],123,(2,3))

arguments : 1 2 ([3, 4, 5], 123, (2, 3))


In [17]:
function varargs(n, m, args...)
    n, m, args
end
α, β, γ = varargs(1,2,3,4,5,[2,3])

(1, 2, (3, 4, 5, [2, 3]))

In [19]:
println(α)
println(β)
println(γ)#⟹ A Tuple

1
2
(3, 4, 5, [2, 3])


In [25]:
function varargs2(args...)
    println("arguments2: $args")
end

varargs2 (generic function with 1 method)

In [26]:
varargs2(3,4)

arguments2: (3, 4)


In [31]:
#The difference between these two sentences are apparent
varargs2(3,4,[10,11,12])
varargs2(3,4,[10,11,12]...)

arguments2: (3, 4, [10, 11, 12])
arguments2: (3, 4, 10, 11, 12)


In [29]:
x = (3,4)
varargs2(1,2,x...)

arguments2: (1, 2, 3, 4)


# It's important to realize that, in Julia, all arguments to functions (with the expectation of plain data such as numbers and chars) are PASSED BY REFERENCE. Their values are not copied when they are passed, which means they can be changed from inside the function, and the changes will be visible to the calling code

In [32]:
function insert_elem(arr)
    push!(arr, -10)
end

arr = [2, 3, 4]
insert_elem(arr)

4-element Array{Int64,1}:
   2
   3
   4
 -10

# A function must be defined by the time it is actually called, but it can be used before that in other function definitions.

In [34]:
function mult2(x::Float64, y::Float64)
    println(x,y)
end
mult2(3,4)

LoadError: MethodError: no method matching mult2(::Int64, ::Int64)

In [35]:
mult2(3.,4.)

3.04.0


In [38]:
mult(x, y) = x * y

mult (generic function with 2 methods)

In [39]:
mult(3,4)

12

In [40]:
f(α,β) = α^3 + 2β - α*β

f (generic function with 1 method)

In [42]:
f(5,6)

107

# Optional & keyword arguments

In [43]:
# optional positional arguments
# f(arg = val)
# if no parameter is supplied for arg, then val is taken as the value of arg
f(a, b=5) = a+b

f (generic function with 2 methods)

In [44]:
f(3)

8

In [45]:
f(2,5)

7

In [46]:
f(2,6)

8

In [47]:
f(2, b=3)#> got unsupported keyword argument "b"

LoadError: MethodError: no method matching f(::Int64; b=3)
Closest candidates are:
  f(::Any) at In[43]:4 got unsupported keyword argument "b"
  f(::Any, !Matched::Any) at In[43]:4 got unsupported keyword argument "b"

In [48]:
#optional keyword arguments
k(x; a1 = 1, a2 = 2) = x * (a1 + a2)

k (generic function with 1 method)

In [50]:
k(1,a2 = 10, a1=6)

16

In [51]:
k(2,a2=9)

20

In [63]:
function allargs(normal_arg, optional_positional_arg = 2; keyword_arg = "ABC")
    print("normal arg: $normal_arg - ")
    print("optional arg: $optional_positional_arg - ")
    print("keyword arg: $keyword_arg")
end

allargs (generic function with 2 methods)

In [64]:
allargs(1, 3, keyword_arg = 4)

normal arg: 1 - optional arg: 3 - keyword arg: 4

In [68]:
function varargs2(;args...)
    args
end

varargs2 (generic function with 2 methods)

In [71]:
a, b, c = varargs2(k1 = "name1", k2 = "name2", k3= 7)

pairs(::NamedTuple) with 3 entries:
  :k1 => "name1"
  :k2 => "name2"
  :k3 => 7

In [73]:
a

Pair{Symbol,Any}(:k1, "name1")

In [78]:
# Anonymous functions
g = (x, y) -> x^3 - y + x * y

g(3,2)

31

In [80]:
(x) -> x + 2

#19 (generic function with 1 method)

In [85]:
g2 = () -> println("Hello, Julia")

#25 (generic function with 1 method)

In [87]:
g2()

Hello, Julia


In [89]:
newton = (Mass, Acceleration) -> Mass * Acceleration

#28 (generic function with 1 method)

In [90]:
newton(1,2)

2

# First-class functions and closures

In [2]:
function mult(x,y)
    println("x is $x and y is $y")
    if x == 1
        return y
    end
    x * y
end
m = mult # Functions can also be assigned to a variable by their names
m(6,6)

x is 6 and y is 6


36

In [3]:
c = x -> x + 2#非常灵活

#1 (generic function with 1 method)

In [4]:
c(5)

7

In [10]:
plusthree = function (x) x + 3 end#怎么写都可以

#7 (generic function with 1 method)

In [13]:
plusthree(3)

6

In [14]:
1 + 2

3

In [16]:
+(1, 2)

3

In [27]:
# A function can take a function as its argument, which calcualtes the numerical derivative of a function f
function numerical_derivatie(f, x, dx=0.01)
    derivative = (f(x+dx) - f(x-dx))/(2dx)
    return derivative
end

numerical_derivatie (generic function with 2 methods)

In [29]:
f = x -> 2x^2 + 30x +9
@time println(numerical_derivatie(f, 1, 0.001))

33.99999999999537
  0.005510 seconds (5.83 k allocations: 285.404 KiB)


In [38]:
# A function can also return another function(or multiple functions) as its value
function derivative(f)
    return function(x)
        h = x == 0 ? sqrt(eps(Float64)) : sqrt(eps(Float64)) * x #如果h = x == 0那就 sqrt(eps(Float64))，否则sqrt(eps(Float64)) * x
        xph = x + h
        dx = xph - x
        f1 = f(xph)
        f0 = f(x)
        return (f1 - f0) / dx
    end
end

derivative (generic function with 1 method)

In [30]:
eps(Float64)

2.220446049250313e-16

In [31]:
?eps

search: eps @elapsed expanduser supertypes escape_string setprecision peakflops



```
eps(::Type{T}) where T<:AbstractFloat
eps()
```

Return the *machine epsilon* of the floating point type `T` (`T = Float64` by default). This is defined as the gap between 1 and the next largest value representable by `typeof(one(T))`, and is equivalent to `eps(one(T))`.  (Since `eps(T)` is a bound on the *relative error* of `T`, it is a "dimensionless" quantity like [`one`](@ref).)

# Examples

```jldoctest
julia> eps()
2.220446049250313e-16

julia> eps(Float32)
1.1920929f-7

julia> 1.0 + eps()
1.0000000000000002

julia> 1.0 + eps()/2
1.0
```

---

```
eps(x::AbstractFloat)
```

Return the *unit in last place* (ulp) of `x`. This is the distance between consecutive representable floating point values at `x`. In most cases, if the distance on either side of `x` is different, then the larger of the two is taken, that is

```
eps(x) == max(x-prevfloat(x), nextfloat(x)-x)
```

The exceptions to this rule are the smallest and largest finite values (e.g. `nextfloat(-Inf)` and `prevfloat(Inf)` for [`Float64`](@ref)), which round to the smaller of the values.

The rationale for this behavior is that `eps` bounds the floating point rounding error. Under the default `RoundNearest` rounding mode, if $y$ is a real number and $x$ is the nearest floating point number to $y$, then

$$
|y-x| \leq \operatorname{eps}(x)/2.
$$

# Examples

```jldoctest
julia> eps(1.0)
2.220446049250313e-16

julia> eps(prevfloat(2.0))
2.220446049250313e-16

julia> eps(2.0)
4.440892098500626e-16

julia> x = prevfloat(Inf)      # largest finite Float64
1.7976931348623157e308

julia> x + eps(x)/2            # rounds up
Inf

julia> x + prevfloat(eps(x)/2) # rounds down
1.7976931348623157e308
```

---

```
eps(::Type{DateTime}) -> Millisecond
eps(::Type{Date}) -> Day
eps(::Type{Time}) -> Nanosecond
eps(::TimeType) -> Period
```

Return the smallest unit value supported by the `TimeType`.

# Examples

```jldoctest
julia> eps(DateTime)
1 millisecond

julia> eps(Date)
1 day

julia> eps(Time)
1 nanosecond
```


In [37]:
a = 3
b = 4
c = 5
a >= b ? println("a=$a") : println("b=$b")
c >= b ? println("c=$c") : println("b=$b")

b=4
c=5


In [45]:
f = x -> x^2 + 3 
Idontknow = derivative(f)

#13 (generic function with 1 method)

In [46]:
Idontknow(5)

10.000000095367431

In [47]:
function counter()
    n = 0
    () -> n += 1, () -> n = 0
end

counter (generic function with 1 method)

In [48]:
(addOne, reset) = counter()#n is not defined outside the function!!!!!

(var"#19#21"(Core.Box(0)), var"#20#22"(Core.Box(0)))

In [55]:
println(addOne())
println(addOne())
println(addOne())
println(reset())
println(addOne())
println(n)

9
10
11
0
1


LoadError: UndefVarError: n not defined

In [56]:
#Currying——the technique of translating the evaluation of a function that takes multiple arguments(or a tuple of arguments)
#into evaluating a sequence of functions, each with a single argument.
#E.g.
function add(x)
    return function f(y)
        return x + y
    end
end

add (generic function with 1 method)

In [59]:
temp = add(5)
temp(6)#这是一种比较直接的用法，下面还有更牛逼的用法

11

In [61]:
add(3)(4)#我直接不要名字了，直接出结果！！ 我下面还能给出更加厉害的写法

7

In [65]:
add1(x) = y -> x + y
add1(5)(7)

12

In [66]:
add2(x) = f(y) = x + y
add2(7)(8)

15

Currying is especially useful when passing functions around, as we will see in the `Map`,`filter` and `list` `comprehensions` section

In [69]:
#在函数里面定义函数并且调用，闻所未闻！
#nest⟹嵌套
function target(x)
    z = x * 2
    function temp(z)
        z += 1
    end
    temp(z)
end

d = 5
target(d)

11

In [70]:
sum(n) = n > 1 ? sum(n-1) + n : n #如果大于1就sum(n-1) + n，否则就是n

sum (generic function with 1 method)

In [71]:
fib(n) = n < 2 ? n : fib(n-1) + fib(n-2) #1 1 2 4 6
fib(3)

2

In [74]:
fib(0)

0

# Broadcasting

In [75]:
#用好Broadcasting很重要！！
arr = [1.0, 2.0, 3.0]
sin.(arr)

3-element Array{Float64,1}:
 0.8414709848078965
 0.9092974268256817
 0.1411200080598672

In [78]:
g(x, y) = x + 7y
g.(pi, arr)

3-element Array{Float64,1}:
 10.141592653589793
 17.141592653589793
 24.141592653589793

# Map, filter and list comprehensions

In [79]:
map(x -> x * 10, [1, 2, 3])

3-element Array{Int64,1}:
 10
 20
 30

In [80]:
cubes = map(x -> Base.power_by_squaring(x, 3), collect(1:5)) # map(函数，众多待被作用对象)

5-element Array{Int64,1}:
   1
   8
  27
  64
 125

In [81]:
map(*, [1, 2, 3] , [4, 5, 6]) # map(运算符， 众多待作用对象， 众多待作用对象)

3-element Array{Int64,1}:
  4
 10
 18

In [82]:
map( x -> begin
            if x == 0 return 0
            elseif iseven(x) return 2
            elseif isodd(x) return 1
            end
        end,collect(-3:3))

7-element Array{Int64,1}:
 1
 2
 1
 0
 1
 2
 1

In [83]:
map(collect(-3:3)) do x
    if x == 0 return 0
    elseif iseven(x) return 2
    elseif isodd(x) return 1
        end
    end

7-element Array{Int64,1}:
 1
 2
 1
 0
 1
 2
 1

In [84]:
filter( n -> iseven(n), collect(1:10)) #顾名思义！用来过滤！

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [85]:
arr = Float64[x^2 for x in 1:4]

4-element Array{Float64,1}:
  1.0
  4.0
  9.0
 16.0

In [86]:
cubes = [x^3 for x in collect(1:5)]

5-element Array{Int64,1}:
   1
   8
  27
  64
 125

In [88]:
mat1 = [x + y for x in 1:2, y in 1:3]

2×3 Array{Int64,2}:
 2  3  4
 3  4  5

In [89]:
table10 = [x * y for x = 1:10, y = 1:10]

10×10 Array{Int64,2}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

In [91]:
arrany = Any[i*2 for i in 1:5]

5-element Array{Any,1}:
  2
  4
  6
  8
 10

# Generic functions and multiple dispatch

In Julia, a concrete version of a function for a specific combination of argument types is called a `method`. To define a new method for a function(also called overloading).

In [93]:
α(n, m) = "base case"
α(n::Number, m::Number) = "n and m are both numbers"
α(n::Number, m) = "n is a number"
α(n, m::Number) = "m is a number"
α(n::Integer, m::Integer) = "n and m are both integers"

α (generic function with 5 methods)

In [94]:
α(1,2)

"n and m are both integers"

In [95]:
α(1,[2,3])

"n is a number"

In [96]:
α([2,3],2)

"m is a number"

In [97]:
α(1,2.2)

"n and m are both numbers"

In [98]:
α("fuck you",[23,2])

"base case"

In [99]:
methods(α) # 快速查看具体的method定义

# 5 methods for generic function "α":
[1] α(n::Integer, m::Integer) in Main at In[93]:5
[2] α(n::Number, m::Number) in Main at In[93]:2
[3] α(n::Number, m) in Main at In[93]:3
[4] α(n, m::Number) in Main at In[93]:4
[5] α(n, m) in Main at In[93]:1

In [100]:
@which α(3,"what?") #利用@which来查看具体用了哪种method

α(n::Number, m) in Main at In[93]:3

In [101]:
"""
Type stability is crucial for optimal performance. A function is type-stable if the return type(s) of 
all the output can be deduced from the types of the inputs.
⟹So try to design your functions with type stability in mind.
"""

@time fib(35)

  0.078474 seconds


9227465

In [102]:
@elapsed fib(35)

0.074078575